POST http://localhost:9000/user/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin" 
}
###
POST http://localhost:9000/user/logout
Content-Type: application/json
{
    
}

###
GET http://localhost:9000/posts
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiYWRtaW4ifSwiaWF0IjoxNjgzODI4MTM0LCJleHAiOjE2ODM4MzE3MzR9.kESL4Qq6KiOezL-xVprjw8Csl44sRoayb7QtQatoZxc

###
GET http://localhost:9000/user/v1